"""Ajout des champs aéroport, state, tail_num, flight_number

Revision ID: 0b02e99c0ec7
Revises: 55228e30a8fa
Create Date: 2025-07-25 08:00:14.952484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b02e99c0ec7'
down_revision: Union[str, None] = '55228e30a8fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbr', sa.String(length=4), nullable=False),
    sa.Column('fips', sa.String(length=8), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr')
    )
    op.add_column('airport', sa.Column('city_name', sa.String(length=64), nullable=True))
    op.add_column('airport', sa.Column('wac', sa.Integer(), nullable=True))
    op.add_column('airport', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'airport', 'state', ['state_id'], ['id'])
    op.add_column('flight', sa.Column('tail_num', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flight', 'tail_num')
    op.drop_constraint(None, 'airport', type_='foreignkey')
    op.drop_column('airport', 'state_id')
    op.drop_column('airport', 'wac')
    op.drop_column('airport', 'city_name')
    op.drop_table('state')
    # ### end Alembic commands ###
