"""Initial migration for new flight model

Revision ID: 55228e30a8fa
Revises: 
Create Date: 2025-07-22 16:25:46.263804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55228e30a8fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('carrier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('airline_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('airline_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('time_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('flight_number', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('origin_id', sa.Integer(), nullable=False),
    sa.Column('dest_id', sa.Integer(), nullable=False),
    sa.Column('dep_time_blk_id', sa.Integer(), nullable=True),
    sa.Column('arr_time_blk_id', sa.Integer(), nullable=True),
    sa.Column('crs_dep_time', sa.String(length=4), nullable=True),
    sa.Column('dep_time', sa.String(length=4), nullable=True),
    sa.Column('dep_delay', sa.Float(), nullable=True),
    sa.Column('dep_delay_new', sa.Float(), nullable=True),
    sa.Column('dep_del15', sa.Boolean(), nullable=True),
    sa.Column('dep_delay_group', sa.SmallInteger(), nullable=True),
    sa.Column('taxi_out', sa.Float(), nullable=True),
    sa.Column('wheels_off', sa.String(length=4), nullable=True),
    sa.Column('wheels_on', sa.String(length=4), nullable=True),
    sa.Column('taxi_in', sa.Float(), nullable=True),
    sa.Column('crs_arr_time', sa.String(length=4), nullable=True),
    sa.Column('arr_time', sa.String(length=4), nullable=True),
    sa.Column('arr_delay', sa.Float(), nullable=True),
    sa.Column('arr_delay_new', sa.Float(), nullable=True),
    sa.Column('arr_del15', sa.Boolean(), nullable=True),
    sa.Column('arr_delay_group', sa.SmallInteger(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancellation_code', sa.String(length=1), nullable=True),
    sa.Column('diverted', sa.Boolean(), nullable=True),
    sa.Column('crs_elapsed_time', sa.Float(), nullable=True),
    sa.Column('actual_elapsed_time', sa.Float(), nullable=True),
    sa.Column('air_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['arr_time_blk_id'], ['time_block.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.id'], ),
    sa.ForeignKeyConstraint(['dep_time_blk_id'], ['time_block.id'], ),
    sa.ForeignKeyConstraint(['dest_id'], ['airport.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['airport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight')
    op.drop_table('time_block')
    op.drop_table('carrier')
    op.drop_table('airport')
    # ### end Alembic commands ###
