"""Initial migration model cleaned

Revision ID: fd0de9acb782
Revises: 
Create Date: 2025-07-16 10:51:10.690539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0de9acb782'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marital_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('native_country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('occupation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('workclass_id', sa.Integer(), nullable=True),
    sa.Column('education_id', sa.Integer(), nullable=True),
    sa.Column('marital_status_id', sa.Integer(), nullable=True),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('capital_gain', sa.Integer(), nullable=True),
    sa.Column('capital_loss', sa.Integer(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('native_country_id', sa.Integer(), nullable=True),
    sa.Column('class_label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_label_id'], ['class_label.id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], ),
    sa.ForeignKeyConstraint(['marital_status_id'], ['marital_status.id'], ),
    sa.ForeignKeyConstraint(['native_country_id'], ['native_country.id'], ),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupation.id'], ),
    sa.ForeignKeyConstraint(['workclass_id'], ['workclass.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.drop_table('workclass')
    op.drop_table('occupation')
    op.drop_table('native_country')
    op.drop_table('marital_status')
    op.drop_table('education')
    op.drop_table('class_label')
    # ### end Alembic commands ###
